const express = require('express');
const router = express.Router();

const UserRoutes = require('./UserRoutes');
const CompanyRoutes = require('./CompanyRoutes');
const SubscriptionPlanRoutes = require('./SubscriptionPlanRoutes');
const SupportTicketRoutes = require('./SupportTicketRoutes');
const BillingRecordRoutes = require('./BillingRecordRoutes');
const AuditLogRoutes = require('./AuditLogRoutes');
const WhiteLabelConfigRoutes = require('./WhiteLabelConfigRoutes');
const FeatureRoutes = require('./FeatureRoutes');
const PlanFeatureRoutes = require('./PlanFeatureRoutes');
const BranchRoutes = require('./BranchRoutes');
const DriverRoutes = require('./DriverRoutes');
const VehicleRoutes = require('./VehicleRoutes');
const LoadRoutes = require('./LoadRoutes');
const TenantSubscriptionRoutes = require('./TenantSubscriptionRoutes');
const PlanVersionLogRoutes = require('./PlanVersionLogRoutes');
const PromoCodeRoutes = require('./PromoCodeRoutes');
const FeatureDependencyRoutes = require('./FeatureDependencyRoutes');
const CompanyFeatureOverrideRoutes = require('./CompanyFeatureOverrideRoutes');
const FeatureVersionLogRoutes = require('./FeatureVersionLogRoutes');
const ThemeRoutes = require('./ThemeRoutes');
const CustomDomainRoutes = require('./CustomDomainRoutes');
const CommunicationTemplateRoutes = require('./CommunicationTemplateRoutes');
const WhiteLabelReleaseLogRoutes = require('./WhiteLabelReleaseLogRoutes');
const ApiIntegrationRoutes = require('./ApiIntegrationRoutes');
const TicketReplyRoutes = require('./TicketReplyRoutes');
const PaymentAttemptRoutes = require('./PaymentAttemptRoutes');
const UserSessionRoutes = require('./UserSessionRoutes');
const ApiUsageLogRoutes = require('./ApiUsageLogRoutes');
const ModuleUsageLogRoutes = require('./ModuleUsageLogRoutes');
const AssetTransferRoutes = require('./AssetTransferRoutes');
const TransferEventLogRoutes = require('./TransferEventLogRoutes');
const AiModuleRoutes = require('./AiModuleRoutes');
const AiActivityLogRoutes = require('./AiActivityLogRoutes');
const CustomRoleRoutes = require('./CustomRoleRoutes');
const CustomPermissionRoutes = require('./CustomPermissionRoutes');
const CompanyIntegrationRoutes = require('./CompanyIntegrationRoutes');
const CustomerRoutes = require('./CustomerRoutes');
const ShiftRoutes = require('./ShiftRoutes');
const ConversationRoutes = require('./ConversationRoutes');
const ConversationParticipantRoutes = require('./ConversationParticipantRoutes');
const MessageRoutes = require('./MessageRoutes');
const ReportRoutes = require('./ReportRoutes');
const ReportScheduleRoutes = require('./ReportScheduleRoutes');
const TelemetryLogRoutes = require('./TelemetryLogRoutes');
const LeadRoutes = require('./LeadRoutes');
const DemoBookingRoutes = require('./DemoBookingRoutes');
const ProposalRoutes = require('./ProposalRoutes');
const FollowUpTaskRoutes = require('./FollowUpTaskRoutes');
const SalesActivityRoutes = require('./SalesActivityRoutes');
const SalesDashboardRoutes = require('./SalesDashboardRoutes');
const OnboardingHandoverRoutes = require('./OnboardingHandoverRoutes');
const EmailTemplateRoutes = require('./EmailTemplateRoutes');
const RouteStopRoutes = require('./RouteStopRoutes');
const LoadItemRoutes = require('./LoadItemRoutes');
const ProofPhotoRoutes = require('./ProofPhotoRoutes');
const LoadExpenseRoutes = require('./LoadExpenseRoutes');
const LoadActivityRoutes = require('./LoadActivityRoutes');
const CustomerInvoiceRoutes = require('./CustomerInvoiceRoutes');
const WarehouseRoutes = require('./WarehouseRoutes');
const InboundReceiptRoutes = require('./InboundReceiptRoutes');
const ItemMovementRoutes = require('./ItemMovementRoutes');
const AssetRoutes = require('./AssetRoutes');
const AssetAssignmentRoutes = require('./AssetAssignmentRoutes');
const AssetMaintenanceRoutes = require('./AssetMaintenanceRoutes');
const PreStartChecklistRoutes = require('./PreStartChecklistRoutes');
const ChecklistItemResponseRoutes = require('./ChecklistItemResponseRoutes');
const TimesheetRoutes = require('./TimesheetRoutes');
const TimesheetEventRoutes = require('./TimesheetEventRoutes');
const PayPeriodRoutes = require('./PayPeriodRoutes');
const EquipmentSwapRoutes = require('./EquipmentSwapRoutes');
const VinScanEventRoutes = require('./VinScanEventRoutes');
const DeliveryPODRoutes = require('./DeliveryPODRoutes');
const OfflineSyncItemRoutes = require('./OfflineSyncItemRoutes');
const LoadLaneRoutes = require('./LoadLaneRoutes');
const StagingAreaRoutes = require('./StagingAreaRoutes');
const NetworkedPrinterRoutes = require('./NetworkedPrinterRoutes');
const WarehouseLabelPrintRoutes = require('./WarehouseLabelPrintRoutes');
const PrintSpoolerJobRoutes = require('./PrintSpoolerJobRoutes');
const authRoutes = require('./AuthRoutes');
const DocumentRoutes = require('./DocumentRoutes');
const PerformanceLogRoutes = require('./PerformanceLogRoutes');
const DriverAllowanceRoutes = require('./DriverAllowanceRoutes');
const DriverDeductionRoutes = require('./DriverDeductionRoutes');
const DriverLeaveRequestRoutes = require('./DriverLeaveRequestRoutes');
const DriverPayRateRoutes = require('./DriverPayRateRoutes');
const DriverActivityRoutes = require('./DriverActivityRoutes');
const DriverMessageRoutes = require('./DriverMessageRoutes');
const DriverSuperInfoRoutes = require('./DriverSuperInfoRoutes');
const SuperAdminDashboardRoutes = require('./SuperAdminDashboardRoutes');
const PaymentGatewayConfigRoutes = require('./PaymentGatewayConfigRoutes');
const WorkflowRuleRoutes = require('./WorkflowRuleRoutes');
const UploadRoutes = require('./UploadRoutes');
const DriverPortalRoutes = require('./DriverPortalRoutes');

router.use('/upload', UploadRoutes);
router.use('/driver-portal', DriverPortalRoutes);
router.use('/auth', authRoutes);
router.use('/workflow-rules', WorkflowRuleRoutes);
router.use('/companys', CompanyRoutes);
router.use('/companies/branches', BranchRoutes);
router.use('/companies', CompanyRoutes);
router.use('/subscription-plans', SubscriptionPlanRoutes);
router.use('/support-tickets', SupportTicketRoutes);
router.use('/billing-records', BillingRecordRoutes);
router.use('/audit-logs', AuditLogRoutes);
router.use('/users', UserRoutes);
router.use('/white-label-configs', WhiteLabelConfigRoutes);
router.use('/features', FeatureRoutes);
router.use('/plan-features', PlanFeatureRoutes);
router.use('/branchs', BranchRoutes);
router.use('/branches', BranchRoutes);
router.use('/drivers', DriverRoutes);
router.use('/vehicles', VehicleRoutes);
router.use('/loads', LoadRoutes);
router.use('/tenant-subscriptions', TenantSubscriptionRoutes);
router.use('/plan-version-logs', PlanVersionLogRoutes);
router.use('/promo-codes', PromoCodeRoutes);
router.use('/feature-dependencys', FeatureDependencyRoutes);
router.use('/company-feature-overrides', CompanyFeatureOverrideRoutes);
router.use('/feature-version-logs', FeatureVersionLogRoutes);
router.use('/themes', ThemeRoutes);
router.use('/custom-domains', CustomDomainRoutes);
router.use('/communication-templates', CommunicationTemplateRoutes);
router.use('/white-label-release-logs', WhiteLabelReleaseLogRoutes);
router.use('/api-integrations', ApiIntegrationRoutes);
router.use('/ticket-replies', TicketReplyRoutes);
router.use('/payment-attempts', PaymentAttemptRoutes);
router.use('/user-sessions', UserSessionRoutes);
router.use('/api-usage-logs', ApiUsageLogRoutes);
router.use('/module-usage-logs', ModuleUsageLogRoutes);
router.use('/asset-transfers', AssetTransferRoutes);
router.use('/transfer-event-logs', TransferEventLogRoutes);
router.use('/ai-modules', AiModuleRoutes);
router.use('/ai-activity-logs', AiActivityLogRoutes);
router.use('/custom-roles', CustomRoleRoutes);
router.use('/custom-permissions', CustomPermissionRoutes);
router.use('/company-integrations', CompanyIntegrationRoutes);
router.use('/customers', CustomerRoutes);
router.use('/shifts', ShiftRoutes);
router.use('/conversations', ConversationRoutes);
router.use('/conversation-participants', ConversationParticipantRoutes);
router.use('/messages', MessageRoutes);
router.use('/reports', ReportRoutes);
router.use('/report-schedules', ReportScheduleRoutes);
router.use('/telemetry-logs', TelemetryLogRoutes);
router.use('/leads', LeadRoutes);
router.use('/demo-bookings', DemoBookingRoutes);
router.use('/proposals', ProposalRoutes);
router.use('/follow-up-tasks', FollowUpTaskRoutes);
router.use('/sales-activitys', SalesActivityRoutes);
router.use('/sales-dashboard', SalesDashboardRoutes);
router.use('/onboarding-handovers', OnboardingHandoverRoutes);
router.use('/email-templates', EmailTemplateRoutes);
router.use('/route-stops', RouteStopRoutes);
router.use('/load-items', LoadItemRoutes);
router.use('/proof-photos', ProofPhotoRoutes);
router.use('/load-expenses', LoadExpenseRoutes);
router.use('/load-activitys', LoadActivityRoutes);
router.use('/customer-invoices', CustomerInvoiceRoutes);
router.use('/warehouses', WarehouseRoutes);
router.use('/inbound-receipts', InboundReceiptRoutes);
router.use('/item-movements', ItemMovementRoutes);
router.use('/assets', AssetRoutes);
router.use('/asset-assignments', AssetAssignmentRoutes);
router.use('/asset-maintenances', AssetMaintenanceRoutes);
router.use('/pre-start-checklists', PreStartChecklistRoutes);
router.use('/checklist-item-responses', ChecklistItemResponseRoutes);
router.use('/timesheets', TimesheetRoutes);
router.use('/timesheet-events', TimesheetEventRoutes);
router.use('/pay-periods', PayPeriodRoutes);
router.use('/equipment-swaps', EquipmentSwapRoutes);
router.use('/vin-scan-events', VinScanEventRoutes);
router.use('/delivery-pods', DeliveryPODRoutes);
router.use('/offline-sync-items', OfflineSyncItemRoutes);
router.use('/load-lanes', LoadLaneRoutes);
router.use('/staging-areas', StagingAreaRoutes);
router.use('/networked-printers', NetworkedPrinterRoutes);
router.use('/warehouse-label-prints', WarehouseLabelPrintRoutes);
router.use('/print-spooler-jobs', PrintSpoolerJobRoutes);
router.use('/documents', DocumentRoutes);
router.use('/performance-logs', PerformanceLogRoutes);
router.use('/driver-allowances', DriverAllowanceRoutes);
router.use('/driver-deductions', DriverDeductionRoutes);
router.use('/driver-leave-requests', DriverLeaveRequestRoutes);
router.use('/driver-pay-rates', DriverPayRateRoutes);
router.use('/driver-activities', DriverActivityRoutes);
router.use('/driver-messages', DriverMessageRoutes);
router.use('/driver-super-info', DriverSuperInfoRoutes);
const CompanyAdminDashboardRoutes = require('./CompanyAdminDashboardRoutes');
const CompanyAdminPortalRoutes = require('./CompanyAdminPortalRoutes');
const AiModelRoutes = require('./AiModelRoutes');
const NotificationTemplateRoutes = require('./NotificationTemplateRoutes');
const NotificationRuleRoutes = require('./NotificationRuleRoutes');
const RecipientGroupRoutes = require('./RecipientGroupRoutes');

const WarehousePortalRoutes = require('./WarehousePortalRoutes');
const RegionalTerminalRoutes = require('./RegionalTerminalRoutes');

router.use('/ai-models', AiModelRoutes);
router.use('/notification-templates', NotificationTemplateRoutes);
router.use('/notification-rules', NotificationRuleRoutes);
router.use('/recipient-groups', RecipientGroupRoutes);
router.use('/terminals', RegionalTerminalRoutes);
router.use('/regional-terminals', RegionalTerminalRoutes);

router.use('/company-admin', CompanyAdminPortalRoutes);
router.use('/company-admin/dashboard', CompanyAdminDashboardRoutes);
router.use('/super-admin/dashboard', SuperAdminDashboardRoutes);
router.use('/payment-gateway-config', PaymentGatewayConfigRoutes);
router.use('/dashboard-metrics', SuperAdminDashboardRoutes);

// Warehouse Portal routes & aliases
router.use('/warehouse-portal', WarehousePortalRoutes);

// Accounts Portal dedicated routes
const AccountsPortalRoutes = require('./AccountsPortalRoutes');
router.use('/accounts', AccountsPortalRoutes);
router.use('/accounts-portal', AccountsPortalRoutes);

// Direct menu aliases for top-level routes
router.use('/live-tracking', CompanyAdminPortalRoutes);
router.use('/pricing', CompanyAdminPortalRoutes);
router.use('/payroll', CompanyAdminPortalRoutes);
router.use('/finance', CompanyAdminPortalRoutes);
router.use('/knowledge-base', CompanyAdminPortalRoutes);
router.use('/roles-permissions', CompanyAdminPortalRoutes);
router.use('/company-settings', CompanyAdminPortalRoutes);
router.use('/safety-checklists', CompanyAdminPortalRoutes);
router.use('/delivery-issues', CompanyAdminPortalRoutes);

module.exports = router;

